{
  "def": {
    "DisableHandup": false,
    "DisableCallUser": false,
    "HandupSleepSecond": 1,
    "StuRefreshSecond": 120,
    "StuOnLineRefreshSecond":20,
    "TeaRefreshSecond": 30,
    "DisabelVideoHandupUserNum": 200,
    "DisabelVideoCallUserNum": 200,
    "DisableCallUserNum": 200,
    "UserListCacheMs": 5000,
    "UserListQueryNum": 250,
    "MaxSpeakUser": 8,
    "MaxHandupUser": 30,
    "RoomCleanMaxUser": 200,
    "RoomCleanUserDelSecond": 300,
    "QueryHandupConfDuration": 5,
    "MuteFillStream": true,
    "MuteOptInterval": 3,
    "HeartbeatTimeoutDuration":20,
    "OneSecondHandupCnt":20
  },
  "201": {
    "DisableHandup": false,
    "DisableCallUser": false,
    "HandupSleepSecond": 3,
    "StuRefreshSecond": 120,
    "StuOnLineRefreshSecond":20,
    "TeaRefreshSecond": 15,
    "DisabelVideoHandupUserNum": 200,
    "DisabelVideoCallUserNum": 200,
    "DisableCallUserNum": 200,
    "UserListCacheMs": 5000,
    "UserListQueryNum": 250,
    "MaxSpeakUser": 8,
    "MaxHandupUser": 30,
    "RoomCleanMaxUser": 200,
    "RoomCleanUserDelSecond": 300,
    "OneSecondHandupCnt":20
  },
  "201_kezxs": {
    "DisableHandup": false,
    "DisableCallUser": false,
    "HandupSleepSecond": 3,
    "StuRefreshSecond": 120,
    "StuOnLineRefreshSecond":20,
    "TeaRefreshSecond": 15,
    "DisabelVideoHandupUserNum": 200,
    "DisabelVideoCallUserNum": 200,
    "DisableCallUserNum": 200,
    "UserListCacheMs": 5000,
    "UserListQueryNum": 250,
    "MaxSpeakUser": 8,
    "MaxHandupUser": 10,
    "RoomCleanMaxUser": 200,
    "RoomCleanUserDelSecond": 300,
    "OneSecondHandupCnt":20
  },
  "101": {
    "DisableHandup": false,
    "DisableCallUser": false,
    "HandupSleepSecond": 2,
    "StuRefreshSecond": 300,
    "StuOnLineRefreshSecond":10,
    "TeaRefreshSecond": 10,
    "DisabelVideoHandupUserNum": 200,
    "DisabelVideoCallUserNum": 200,
    "DisableCallUserNum": 200,
    "UserListCacheMs": 1000,
    "UserListQueryNum": 250,
    "MaxSpeakUser": 6,
    "MaxHandupUser": 40,
    "RoomCleanMaxUser": 200,
    "RoomCleanUserDelSecond": 300,
    "OneSecondHandupCnt":20
  }
}