// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package twire

// Injectors from wire.go:

func InitApp(dsn string) (*App, error) {
	bussInfra, err := NewBussInfra(dsn)
	if err != nil {
		return nil, err
	}
	service := NewService(bussInfra)
	app, err := NewApp(service, bussInfra)
	if err != nil {
		return nil, err
	}
	return app, nil
}
