package ability

type LevelDesc struct {
	DescKeyword string `json:"desc_keyword"`
	DescRemark  string `json:"desc_remark"`
	LevelName   string `json:"model_level_name"`
}

type Item struct {
	ItemId        int         `json:"item_id"`
	ItemName      string      `json:"item_name"`
	ItemRemark    string      `json:"item_remark"`
	IsStandard    int         `json:"is_standard"`
	TypeName      string      `json:"type_name"`
	LevelDescList []LevelDesc `json:"ability_level_desc_list"`
}

type Data struct {
	AbilityItems []Item `json:"ability_items"`
}

type Json struct {
	Data Data `json:"data"`
}

type AutoGenerated struct {
	Success bool `json:"success"`
	Data    struct {
		ModelID       int    `json:"model_id"`
		AppCode       string `json:"app_code"`
		ParentModelID int    `json:"parent_model_id"`
		BusinessID    string `json:"business_id"`
		ModelCode     string `json:"model_code"`
		ModelName     string `json:"model_name"`
		ModelRemark   string `json:"model_remark"`
		VersionID     int    `json:"version_id"`
		VersionCode   string `json:"version_code"`
		AbilityItems  []struct {
			ItemID                  int    `json:"item_id"`
			AppCode                 string `json:"app_code"`
			TypeID                  int    `json:"type_id"`
			ItemCode                string `json:"item_code"`
			ItemName                string `json:"item_name"`
			ItemRemark              string `json:"item_remark"`
			ItemType                int    `json:"item_type"`
			IsStandard              int    `json:"is_standard"`
			ModelID                 int    `json:"model_id"`
			ModelCode               string `json:"model_code"`
			ParentModelID           int    `json:"parent_model_id"`
			TypeName                string `json:"type_name"`
			RuleCode                string `json:"rule_code"`
			RelationOfModelItemRate int    `json:"relation_of_model_item_rate,omitempty"`
			AbilityLevelDescList    []struct {
				DescID                  int    `json:"desc_id"`
				DescCode                string `json:"desc_code"`
				AppCode                 string `json:"app_code"`
				ItemID                  int    `json:"item_id"`
				AbilityLevelID          int    `json:"ability_level_id"`
				DescKeyword             string `json:"desc_keyword"`
				DescRemark              string `json:"desc_remark"`
				ModelLevelID            int    `json:"model_level_id"`
				ModelLevelCode          string `json:"model_level_code"`
				ModelLevelName          string `json:"model_level_name"`
				ModelLevelValue         int    `json:"model_level_value"`
				RelationOfLevelDescRate int    `json:"relation_of_level_desc_rate"`
				ModelID                 int    `json:"model_id"`
				ParentModelID           int    `json:"parent_model_id"`
			} `json:"ability_level_desc_list"`
			RelationOfModelItemRemark string `json:"relation_of_model_item_remark,omitempty"`
		} `json:"ability_items"`
		RuleID           int    `json:"rule_id"`
		RuleCode         string `json:"rule_code"`
		RuleName         string `json:"rule_name"`
		BaseInfoFullName string `json:"base_info_full_name"`
	} `json:"data"`
	Code int `json:"code"`
}
