version: "3"
services:
    redis:
        build: ./redis
        ports:
            - "6379:6379"
        networks:
            - frontend
        volumes:
            - redis-data:/data
        restart: on-failure
        sysctls:
            net.core.somaxconn: 1024
    goworker:
        image: alpine:latest
        networks:
            - frontend
        entrypoint: ["tail", "-f", "/dev/null"]
networks:
    frontend:
volumes:
    redis-data:
