// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package greet

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

// InitializeEvent 就是一个“注入器”，现在我们已经完成了注入器，我们可以使用wire命令行工具了。
// InitializeEvent 注入器的目的是提供有关使用哪些提供程序来构建一个的信息Event
// 因此我们将在文件顶部使用构建约束将其从最终二进制文件中排除
func InitializeEventRobot(robotID string) Event {
	message := NewMessage()
	robotGreeter := NewRobotGreeter(message, robotID)
	event := NewEvent(robotGreeter)
	return event
}

func InitializeEventHuman() Event {
	message := NewMessage()
	humanGreeter := NewHumanGreeter(message)
	event := NewEvent(humanGreeter)
	return event
}

// wire.go:

var MessageSet = wire.NewSet(
	NewMessage,
	NewEvent,
)

var humanSet = wire.NewSet(
	NewHumanGreeter, wire.Bind(new(Speaker), new(HumanGreeter)),
)

var robotSet = wire.NewSet(
	NewRobotGreeter, wire.Bind(new(Speaker), new(*RobotGreeter)),
)
