package texcel

import (
	"encoding/json"
	"io/ioutil"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"x-learn/third/texcel/ability"
)

func TestExcelDump(t *testing.T) {
	file, err := os.OpenFile("./ability/ability.json", os.O_RDONLY, 0600)
	assert.Nil(t, err)
	data, err := ioutil.ReadAll(file)
	assert.Nil(t, err)

	// JSON.data.ability_items[0].ability_level_desc_list[5].desc_remark
	var jd ability.AutoGenerated
	err = json.Unmarshal(data, &jd)
	if err != nil {
		t.Errorf("%s", err)
	}
	assert.Nil(t, err, err)

	t.Logf("%+v", jd)
}
