client:
  filter:                                          #针对所有后端调用函数前后的拦截器列表
    - m007
    - trpc_edu_log
    - cm
    - jaeger
  service:
    - name: go_edu_push_adapter     #后端服务的service name
      namespace: Production
      network: tcp                             #后端服务的网络类型 tcp udp 配置优先
      target: polaris://trpc.base.go_svr_base_push_proxy.bytes
      protocol: qapp
      timeout: 5000
    - name: trpc.CSIG_EDU_MEDIA_SERVICE.go_edu_media_service_proxy.edu_media_service_proxy #后端服务的service name
      namespace: Production                   #后端服务的环境
      network: tcp                             #后端服务的网络类型 tcp udp 配置优先
      protocol: trpc               #应用层协议 trpc http
      target: polaris://trpc.CSIG_EDU_MEDIA_SERVICE.go_edu_media_service_proxy.edu_media_service_proxy             #请求服务地址
      timeout: 5000
    - name: trpc.CSIG_EDU_MEDIA_SERVICE.go_edu_mix_stream.edu_mix_stream
      namespace: Production                   #后端服务的环境
      network: tcp                             #后端服务的网络类型 tcp udp 配置优先
      protocol: trpc               #应用层协议 trpc http
      target: polaris://trpc.CSIG_EDU_MEDIA_SERVICE.go_edu_mix_stream.ke_mix_stream             #请求服务地址
      timeout: 5000
    - name: go_edu_info_read
      namespace: Production
      protocol: qapp
      target: polaris://bingo.ketang.go_edu_info_read_svr.qapp            #请求服务地址
      timeout: 5000