### 请求服务端，生成相关diam
POST http://127.0.0.1:3000/api/v1/comments
Content-Type: application/json'

{ "text":"hey, man" }

### 请求服务端，
POST http://localhost:3000/api/v1/comments
Content-Type: application/json'

{ "text":"keep up the good work" }