// Code generated by MockGen. DO NOT EDIT.
// Source: foo.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIApolloConfig is a mock of IApolloConfig interface
type MockIApolloConfig struct {
	ctrl     *gomock.Controller
	recorder *MockIApolloConfigMockRecorder
}

// MockIApolloConfigMockRecorder is the mock recorder for MockIApolloConfig
type MockIApolloConfigMockRecorder struct {
	mock *MockIApolloConfig
}

// NewMockIApolloConfig creates a new mock instance
func NewMockIApolloConfig(ctrl *gomock.Controller) *MockIApolloConfig {
	mock := &MockIApolloConfig{ctrl: ctrl}
	mock.recorder = &MockIApolloConfigMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIApolloConfig) EXPECT() *MockIApolloConfigMockRecorder {
	return m.recorder
}

// GetConfig mocks base method
func (m *MockIApolloConfig) GetConfig(key string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConfig", key)
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetConfig indicates an expected call of GetConfig
func (mr *MockIApolloConfigMockRecorder) GetConfig(key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConfig", reflect.TypeOf((*MockIApolloConfig)(nil).GetConfig), key)
}
